TABLES PA0001.

*STRUCTURE DECLARATION*

TYPES: BEGIN OF TY_PA0001,
         MANDT TYPE PA0001-MANDT,
         PERNR TYPE PA0001-PERNR,
         ENDDA TYPE PA0001-ENDDA,
         BEGDA TYPE PA0001-BEGDA,
         UNAME TYPE PA0001-UNAME,
         SNAME TYPE PA0001-SNAME,
       END OF TY_PA0001.

*INTERNAL TABLE AND WORKAREA DECLARATION*

DATA: IT_PA0001 TYPE TABLE OF TY_PA0001,
      WA_PA0001 TYPE TY_PA0001,
      LV_PERNR  TYPE PA0001-PERNR,
      IT_FCAT   TYPE SLIS_T_FIELDCAT_ALV,
      WA_FCAT   TYPE SLIS_FIELDCAT_ALV,
      WA_LAYO   TYPE SLIS_LAYOUT_ALV.

*SELECTION SCREEN DESIGNING*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

SELECT-OPTIONS: SO_PERNR FOR LV_PERNR NO INTERVALS.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN PUSHBUTTON 32(15) B2 USER-COMMAND FC1.

INITIALIZATION.
  B2 = 'DOWNLOAD'.

*FETCHING THE DATA*

  SELECT MANDT
         PERNR
         ENDDA
         BEGDA
         UNAME
         SNAME
  FROM PA0001 INTO TABLE IT_PA0001 WHERE PERNR IN SO_PERNR.

*FIELDCATALOG DESIGNING*

  WA_FCAT-COL_POS = '1'.
  WA_FCAT-FIELDNAME = 'MANDT'.
  WA_FCAT-SELTEXT_L = 'CLIENT'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_FCAT-COL_POS = '2'.
  WA_FCAT-FIELDNAME = 'PERNR'.
  WA_FCAT-SELTEXT_L = 'PERSONNEL NUMBER'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_FCAT-COL_POS = '3'.
  WA_FCAT-FIELDNAME = 'ENDDA'.
  WA_FCAT-SELTEXT_L = 'END DATE'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_FCAT-COL_POS = '4'.
  WA_FCAT-FIELDNAME = 'BEGDA'.
  WA_FCAT-SELTEXT_L = 'BEGIN DATE'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_FCAT-COL_POS = '5'.
  WA_FCAT-FIELDNAME = 'UNAME'.
  WA_FCAT-SELTEXT_L = 'USER NAME'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_FCAT-COL_POS = '6'.
  WA_FCAT-FIELDNAME = 'SNAME'.
  WA_FCAT-SELTEXT_L = 'EMPLOYEE NAME'.
  WA_FCAT-EDIT = 'X'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_LAYO-COLWIDTH_OPTIMIZE = 'X'.
  WA_LAYO-ZEBRA = 'X'.

*DISPLAY THE DATA*

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      IS_LAYOUT   = WA_LAYO
      IT_FIELDCAT = IT_FCAT
    TABLES
      T_OUTTAB    = IT_PA0001.

AT SELECTION-SCREEN.
  CASE SY-UCOMM.
    WHEN 'FC1'.

      CALL FUNCTION 'SAP_CONVERT_TO_XLS_FORMAT'
        EXPORTING
          I_FIELD_SEPERATOR = '#'
          I_LINE_HEADER     = 'X'
          I_FILENAME        = 'Export.xls'
        TABLES
          I_TAB_SAP_DATA    = IT_PA0001
        EXCEPTIONS
          CONVERSION_FAILED = 1.

  ENDCASE.
