TABLES PA0001.

*STRUCTURE DECLARATION*

TYPES: BEGIN OF TY_PA0001,
         MANDT TYPE PA0001-MANDT,
         PERNR TYPE PA0001-PERNR,
         ENDDA TYPE PA0001-ENDDA,
         BEGDA TYPE PA0001-BEGDA,
         UNAME TYPE PA0001-UNAME,
         SNAME TYPE PA0001-SNAME,
       END OF TY_PA0001.

*INTERNAL TABLE AND WORKAREA DECLARATION*

DATA: IT_PA0001 TYPE TABLE OF TY_PA0001,
      WA_PA0001 TYPE TY_PA0001,
      LV_PERNR  TYPE PA0001-PERNR,
      IT_FCAT   TYPE SLIS_T_FIELDCAT_ALV,
      WA_FCAT   TYPE SLIS_FIELDCAT_ALV,
      WA_LAYO   TYPE SLIS_LAYOUT_ALV.

*HEADER*

DATA: BEGIN OF WA_HEADER,
        NAME TYPE C LENGTH 100,
      END OF WA_HEADER.

DATA: T_HEADER LIKE TABLE OF WA_HEADER.

*SELECTION SCREEN DESIGNING*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

SELECT-OPTIONS: SO_PERNR FOR LV_PERNR.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN PUSHBUTTON 32(15) B2 USER-COMMAND FC1.

INITIALIZATION.
  B2 = 'DOWNLOAD'.

*SUBROUTINES*

START-OF-SELECTION.
  PERFORM F_PROCESS_DATA.
*  PERFORM F_DOWNLOAD.

FORM F_PROCESS_DATA .

*FETCHING THE DATA*

  SELECT MANDT
         PERNR
         ENDDA
         BEGDA
         UNAME
         SNAME
  FROM PA0001 INTO TABLE IT_PA0001 WHERE PERNR IN SO_PERNR.

*FIELDCATALOG DESIGNING*

  WA_FCAT-COL_POS = '1'.
  WA_FCAT-FIELDNAME = 'MANDT'.
  WA_FCAT-SELTEXT_L = 'CLIENT'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_FCAT-COL_POS = '2'.
  WA_FCAT-FIELDNAME = 'PERNR'.
  WA_FCAT-SELTEXT_L = 'PERSONNEL NUMBER'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_FCAT-COL_POS = '3'.
  WA_FCAT-FIELDNAME = 'ENDDA'.
  WA_FCAT-SELTEXT_L = 'END DATE'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_FCAT-COL_POS = '4'.
  WA_FCAT-FIELDNAME = 'BEGDA'.
  WA_FCAT-SELTEXT_L = 'BEGIN DATE'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_FCAT-COL_POS = '5'.
  WA_FCAT-FIELDNAME = 'UNAME'.
  WA_FCAT-SELTEXT_L = 'USER NAME'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_FCAT-COL_POS = '6'.
  WA_FCAT-FIELDNAME = 'SNAME'.
  WA_FCAT-SELTEXT_L = 'EMPLOYEE NAME'.
  WA_FCAT-EDIT = 'X'.
  APPEND WA_FCAT TO IT_FCAT.

  WA_LAYO-COLWIDTH_OPTIMIZE = 'X'.
  WA_LAYO-ZEBRA = 'X'.

*DISPLAY THE DATA*

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      IS_LAYOUT   = WA_LAYO
      IT_FIELDCAT = IT_FCAT
    TABLES
      T_OUTTAB    = IT_PA0001.

ENDFORM.

AT SELECTION-SCREEN.
  CASE SY-UCOMM.
    WHEN 'FC1'.
      PERFORM F_DOWNLOAD.

  ENDCASE.

FORM F_DOWNLOAD .

  SELECT MANDT
         PERNR
         ENDDA
         BEGDA
         UNAME
         SNAME
  FROM PA0001 INTO TABLE IT_PA0001 WHERE PERNR IN SO_PERNR.

  DATA: LV_FILENAME TYPE STRING,
        LV_PATH     TYPE STRING,
        LV_FULLPATH TYPE STRING,
        LV_RESULT   TYPE I,
        LV_DEFAULT  TYPE STRING,
        LV_FNAME    TYPE STRING.

  CALL METHOD CL_GUI_FRONTEND_SERVICES=>FILE_SAVE_DIALOG
    EXPORTING
      WINDOW_TITLE      = 'FILE DIRECTORY'
      DEFAULT_EXTENSION = 'DOC'
      INITIAL_DIRECTORY = 'D:\'
    CHANGING
      FILENAME          = LV_FILENAME
      PATH              = LV_PATH
      FULLPATH          = LV_FULLPATH
      USER_ACTION       = LV_RESULT.

  LV_FNAME = LV_FULLPATH.

*DOWNLOAD FILE IN EXCEL*

  CALL FUNCTION 'GUI_DOWNLOAD'
    EXPORTING
      BIN_FILESIZE = ''
      FILENAME     = LV_FNAME
      FILETYPE     = 'DAT'
    TABLES
      DATA_TAB     = IT_PA0001
      FIELDNAMES   = T_HEADER.

ENDFORM.
