TABLES: T551A,T550A.

TYPE-POOLS: SLIS.

"Structure declartion"

TYPES: BEGIN OF TY_T551A,
         TPRG3 TYPE T551A-TPRG3,
         ZMODN TYPE T551A-ZMODN,
         MOTPR TYPE T550A-MOTPR,
         LV_ID TYPE I,
       END OF TY_T551A,

       BEGIN OF TY_T550A,
         TPROG       TYPE T550A-TPROG,
         SOBEG       TYPE T550A-SOBEG,
         SOEND       TYPE T550A-SOEND,
         MOTPR       TYPE T550A-MOTPR,
         LV_DAYINDEX TYPE I,
       END OF TY_T550A,

       BEGIN OF TY_ALL,
         LV_ID       TYPE I,
         TPRG3       TYPE T551A-TPRG3,
         ZMODN       TYPE T551A-ZMODN,
         TPROG       TYPE T550A-TPROG,
         SOBEG       TYPE T550A-SOBEG,
         SOEND       TYPE T550A-SOEND,
         MOTPR       TYPE T550A-MOTPR,
         LV_DAYINDEX TYPE I,
       END OF TY_ALL.

"Internal Table and work area declartion"

DATA: GT_T551A  TYPE STANDARD TABLE OF TY_T551A,
      WA_T551A  TYPE TY_T551A,

      LV_NUMBER TYPE I,

      LV_MOTPR  TYPE T550A-MOTPR,

      GT_T550A  TYPE STANDARD TABLE OF TY_T550A,
      WA_T550A  TYPE TY_T550A,

      GT_ALL    TYPE STANDARD TABLE OF TY_ALL,
      WA_ALL    TYPE TY_ALL.

DATA: GT_FCAT   TYPE SLIS_T_FIELDCAT_ALV,
      WA_FCAT   LIKE LINE OF GT_FCAT,
      GT_LAYOUT TYPE SLIS_LAYOUT_ALV.

"Header"
DATA: BEGIN OF WA_HEADER,
        NAME TYPE C LENGTH 100,
      END OF WA_HEADER.

DATA: T_HEADER LIKE TABLE OF WA_HEADER.


*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
*
*SELECT-OPTIONS: SO_MOTPR FOR LV_MOTPR .
*
*SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN PUSHBUTTON 32(15) B2 USER-COMMAND FC1.

INITIALIZATION.
  B2 = 'Download'.

  "Subroutines"

START-OF-SELECTION.
  PERFORM F_PROCESS_DATA.
  PERFORM F_DOWNLOAD.


FORM F_PROCESS_DATA .
  SELECT
         TPRG3
         ZMODN
  FROM T551A
  INTO TABLE GT_T551A.

  SELECT TPROG
         SOBEG
*       SOEND
  FROM T550A
  INTO TABLE GT_T550A
  WHERE  MOTPR = '24'.

  LOOP AT GT_T550A INTO WA_T550A.
    WA_ALL-TPROG = WA_T550A-TPROG.
    WA_ALL-SOBEG = WA_T550A-SOBEG.
    WA_ALL-SOEND = WA_T550A-SOEND.
    WA_ALL-MOTPR = WA_T550A-MOTPR.


    READ TABLE GT_T551A INTO WA_T551A WITH KEY MOTPR = WA_T551A-MOTPR.

    IF SY-SUBRC EQ 0.
      WA_ALL-TPRG3 = WA_T551A-TPRG3.
      WA_ALL-ZMODN = WA_T551A-ZMODN.

    ENDIF.
    APPEND WA_ALL TO GT_ALL.
    CLEAR: WA_T551A,WA_T550A,WA_ALL.
  ENDLOOP.


  WA_FCAT-COL_POS = '1'.
  WA_FCAT-FIELDNAME = 'lv_ID'.
  WA_FCAT-SELTEXT_L = 'ID'.
  WA_FCAT-NO_ZERO = 'x'.
  APPEND WA_FCAT TO GT_FCAT.
  CLEAR WA_FCAT.

  WA_FCAT-COL_POS = '2'.
  WA_FCAT-FIELDNAME = 'TPRG3'.
  WA_FCAT-SELTEXT_L = 'Daily Work Schedule'.
  APPEND WA_FCAT TO GT_FCAT.
  CLEAR WA_FCAT.

  WA_FCAT-COL_POS = '3'.
  WA_FCAT-FIELDNAME = 'ZMODN'.
  WA_FCAT-SELTEXT_L = 'Period Work Schedule(Shift)'.
  APPEND WA_FCAT TO GT_FCAT.
  CLEAR WA_FCAT.

  WA_FCAT-COL_POS = '4'.
  WA_FCAT-FIELDNAME = 'TPROG'.
  WA_FCAT-SELTEXT_L = 'Daily Work Schedule'.
  APPEND WA_FCAT TO GT_FCAT.
  CLEAR WA_FCAT.

  WA_FCAT-COL_POS = '5'.
  WA_FCAT-FIELDNAME = 'SOBEG'.
  WA_FCAT-SELTEXT_L = 'Start of planned working time(in_time)'.
  APPEND WA_FCAT TO GT_FCAT.
  CLEAR WA_FCAT.

  WA_FCAT-COL_POS = '6'.
  WA_FCAT-FIELDNAME = 'SOEND'.
  WA_FCAT-SELTEXT_L = 'End of planned working time(out_time)'.
  APPEND WA_FCAT TO GT_FCAT.
  CLEAR WA_FCAT.

  WA_FCAT-COL_POS = '7'.
  WA_FCAT-FIELDNAME = 'MOTPR '.
  WA_FCAT-SELTEXT_L = 'Personnel Subarea Grouping for Daily Work Schedules'.
  APPEND WA_FCAT TO GT_FCAT.
  CLEAR WA_FCAT.

  WA_FCAT-COL_POS = '8'.
  WA_FCAT-FIELDNAME = 'lv_dayindex'.
  WA_FCAT-SELTEXT_L = 'Day_Index'.
  APPEND WA_FCAT TO GT_FCAT.
  CLEAR WA_FCAT.

  GT_LAYOUT-COLWIDTH_OPTIMIZE = 'x'.
  GT_LAYOUT-EDIT = 'x'.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      IS_LAYOUT   = GT_LAYOUT
      IT_FIELDCAT = GT_FCAT
    TABLES
      T_OUTTAB    = GT_ALL.

ENDFORM.

AT SELECTION-SCREEN.
  CASE SY-UCOMM.
    WHEN 'FC1'.
      PERFORM F_DOWNLOAD.

  ENDCASE.

FORM F_DOWNLOAD .
  SELECT
         TPRG3
         ZMODN
  FROM T551A
  INTO TABLE GT_T551A.

  SELECT TPROG
         SOBEG
*       SOEND
  FROM T550A
  INTO TABLE GT_T550A
  WHERE  MOTPR = '24'.


  DATA: LV_FILENAME TYPE STRING,
        LV_PATH     TYPE STRING,
        LV_FULLPATH TYPE STRING,
        LV_RESULT   TYPE I,
        LV_DEFAULT  TYPE STRING,
        LV_FNAME    TYPE STRING.

  CALL METHOD CL_GUI_FRONTEND_SERVICES=>FILE_SAVE_DIALOG
    EXPORTING
      WINDOW_TITLE      = 'FILE DIRECTORY'
      DEFAULT_EXTENSION = 'XLS'
      INITIAL_DIRECTORY = 'D:\'
    CHANGING
      FILENAME          = LV_FILENAME
      PATH              = LV_PATH
      FULLPATH          = LV_FULLPATH
      USER_ACTION       = LV_RESULT.

  LV_FNAME = LV_FULLPATH.



  CALL FUNCTION 'GUI_DOWNLOAD'
    EXPORTING
*     BIN_FILESIZE                    = BIN_FILESIZE
      FILENAME   = LV_FNAME
      FILETYPE   = 'DAT'
    TABLES
      DATA_TAB   = GT_ALL
      FIELDNAMES = T_HEADER.




ENDFORM.
